### ISSUE TITLE
Build error with `kernel-pfkey` plug-in: `utils.h: error: size of unnamed array is negative`

### ISSUE THREAD

**Issue by barracuda156** [strongswan/strongswan#2958]
**System (please complete the following information):**
 - OS: macOS 10.6.8
 - Kernel version (if applicable): 1504.15.3
 - strongSwan version(s): 6.0.3

**Describe the bug**
`kernel-pfkey` fails to build with:
```
utils.h: error: size of unnamed array is negative
```

**To Reproduce**
Run the build using the same config options which Homebrew has: https://github.com/Homebrew/homebrew-core/blob/93448d6ae81277a158d0d8b449eb8803efab48a0/Formula/s/strongswan.rb#L45-L81

**Expected behavior**
The build should either succeed with all options, or if something is missing in 10.6 for a given option, configure should detect that and disable (or fail and return a message that such and such option is unsupported on this system and cannot be enabled).

**Logs/Backtraces**
```
Making all in plugins/kernel_pfkey
make[5]: Entering directory `/opt/local/var/macports/build/strongswan-18729cba/work/strongswan-6.0.3/src/libcharon/plugins/kernel_pfkey'
depbase=`echo kernel_pfkey_plugin.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
    /bin/sh ../../../../libtool  --tag=CC   --mode=compile /opt/local/bin/gcc-mp-14 -DHAVE_CONFIG_H -I. -I../../../..  -I../../../../src/include -I../../../../src/libstrongswan -I../../../../src/libcharon -I/opt/local/libexec/openssl3/include -isystem/opt/local/include/LegacySupport -isystem/opt/local/include -I/opt/local/include -rdynamic -Wno-format -Wno-format-security -Wno-implicit-fallthrough -Wno-missing-field-initializers -Wno-pointer-sign -Wno-sign-compare -Wno-type-limits -Wno-unused-parameter -pipe -I/opt/local/libexec/openssl3/include -Os -arch ppc -include /opt/local/var/macports/build/strongswan-18729cba/work/strongswan-6.0.3/config.h -MT kernel_pfkey_plugin.lo -MD -MP -MF $depbase.Tpo -c -o kernel_pfkey_plugin.lo kernel_pfkey_plugin.c &&\
    mv -f $depbase.Tpo $depbase.Plo
depbase=`echo kernel_pfkey_ipsec.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
    /bin/sh ../../../../libtool  --tag=CC   --mode=compile /opt/local/bin/gcc-mp-14 -DHAVE_CONFIG_H -I. -I../../../..  -I../../../../src/include -I../../../../src/libstrongswan -I../../../../src/libcharon -I/opt/local/libexec/openssl3/include -isystem/opt/local/include/LegacySupport -isystem/opt/local/include -I/opt/local/include -rdynamic -Wno-format -Wno-format-security -Wno-implicit-fallthrough -Wno-missing-field-initializers -Wno-pointer-sign -Wno-sign-compare -Wno-type-limits -Wno-unused-parameter -pipe -I/opt/local/libexec/openssl3/include -Os -arch ppc -include /opt/local/var/macports/build/strongswan-18729cba/work/strongswan-6.0.3/config.h -MT kernel_pfkey_ipsec.lo -MD -MP -MF $depbase.Tpo -c -o kernel_pfkey_ipsec.lo kernel_pfkey_ipsec.c &&\
    mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  /opt/local/bin/gcc-mp-14 -DHAVE_CONFIG_H -I. -I../../../.. -I../../../../src/include -I../../../../src/libstrongswan -I../../../../src/libcharon -I/opt/local/libexec/openssl3/include -isystem/opt/local/include/LegacySupport -isystem/opt/local/include -I/opt/local/include -rdynamic -Wno-format -Wno-format-security -Wno-implicit-fallthrough -Wno-missing-field-initializers -Wno-pointer-sign -Wno-sign-compare -Wno-type-limits -Wno-unused-parameter -pipe -I/opt/local/libexec/openssl3/include -Os -arch ppc -include /opt/local/var/macports/build/strongswan-18729cba/work/strongswan-6.0.3/config.h -MT kernel_pfkey_ipsec.lo -MD -MP -MF .deps/kernel_pfkey_ipsec.Tpo -c kernel_pfkey_ipsec.c  -fno-common -DPIC -o .libs/kernel_pfkey_ipsec.o
libtool: compile:  /opt/local/bin/gcc-mp-14 -DHAVE_CONFIG_H -I. -I../../../.. -I../../../../src/include -I../../../../src/libstrongswan -I../../../../src/libcharon -I/opt/local/libexec/openssl3/include -isystem/opt/local/include/LegacySupport -isystem/opt/local/include -I/opt/local/include -rdynamic -Wno-format -Wno-format-security -Wno-implicit-fallthrough -Wno-missing-field-initializers -Wno-pointer-sign -Wno-sign-compare -Wno-type-limits -Wno-unused-parameter -pipe -I/opt/local/libexec/openssl3/include -Os -arch ppc -include /opt/local/var/macports/build/strongswan-18729cba/work/strongswan-6.0.3/config.h -MT kernel_pfkey_plugin.lo -MD -MP -MF .deps/kernel_pfkey_plugin.Tpo -c kernel_pfkey_plugin.c  -fno-common -DPIC -o .libs/kernel_pfkey_plugin.o
In file included from ../../../../src/libstrongswan/networking/host.h:28,
                 from ../../../../src/libcharon/kernel/kernel_ipsec.h:39,
                 from kernel_pfkey_ipsec.h:25,
                 from kernel_pfkey_ipsec.c:80:
../../../../src/libstrongswan/utils/utils.h:104:37: error: size of unnamed array is negative
  104 | #define BUILD_ASSERT(x) (sizeof(char[(x) ? 0 : -1]))
      |                                     ^
../../../../src/libstrongswan/utils/enum.h:84:17: note: in expansion of macro 'BUILD_ASSERT'
   84 |                 BUILD_ASSERT(((last)-(first)+1) == countof(((char*[]){__VA_ARGS__}))), \
      |                 ^~~~~~~~~~~~
../../../../src/libstrongswan/utils/enum.h:121:9: note: in expansion of macro 'ENUM_BEGIN'
  121 |         ENUM_BEGIN(name, first, last, __VA_ARGS__); ENUM_END(name, last)
      |         ^~~~~~~~~~
kernel_pfkey_ipsec.c:721:1: note: in expansion of macro 'ENUM'
  721 | ENUM(sadb_ext_type_names, SADB_EXT_RESERVED, SADB_EXT_MAX,
      | ^~~~
make[5]: *** [kernel_pfkey_ipsec.lo] Error 1
make[5]: Leaving directory `/opt/local/var/macports/build/strongswan-18729cba/work/strongswan-6.0.3/src/libcharon/plugins/kernel_pfkey'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/opt/local/var/macports/build/strongswan-18729cba/work/strongswan-6.0.3/src/libcharon'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/opt/local/var/macports/build/strongswan-18729cba/work/strongswan-6.0.3/src/libcharon'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/strongswan-18729cba/work/strongswan-6.0.3/src'
make[1]: *** [all-recursive] Error 1
```

**Additional context**
Build with MacPorts, gcc 14.3.0, curl 8.13.0

**Comment by barracuda156** [comment]
P. S. This is the only failure, otherwise the build succeeds with `--disable-kernel-pfkey`.

**Comment by tobiasbrunner** [comment]
The enum names [here](https://github.com/strongswan/strongswan/blob/f25b1aca8ba62bdc221b8aa2f86c0dfae0f9d56a/src/libcharon/plugins/kernel_pfkey/kernel_pfkey_ipsec.c#L721) depend on the constants defined in the `pfkeyv2.h` file. Those defined between `SADB_EXT_RESERVED` and `SADB_EXT_MAX`. And we check that all constants have a string assigned. So if you build on a system that has additional extensions defined, there will be a mismatch. I think we currently cover [the public header here](https://github.com/apple-oss-distributions/xnu/blob/main/bsd/net/pfkeyv2.h) correctly, so please check if the header on your system contains any differences.

**Comment by tobiasbrunner** [comment]
Oh, wait. 10.6 was released over 14 years ago, so there are probably too many strings defined and you have to remove some of them. I'll close this though, as supporting such old and unsupported operating systems doesn't really make sense upstream.

**Comment by barracuda156** [comment]
@tobiasbrunner Should I just use `--enable-kernel-libipsec` instead of `--enable-kernel-pfkey`?

I do not insist on fixing the issue here in upstream, but I do support 10.6 in my ports, so it matters :)

**Comment by tobiasbrunner** [comment]
That's up to you. You might want to read up on [that plugin](https://docs.strongswan.org/docs/latest/plugins/kernel-libipsec.html), though.

**Comment by barracuda156** [comment]
Thank you, I will look into that. FWIW, the build with `--enable-kernel-libipsec` works fine.

**Comment by barracuda156** [comment]
@tobiasbrunner Could you please say if these are sufficient for Strongswan? https://github.com/apple-oss-distributions/xnu/blob/99c11f3f90a18f35d3692ea77444b51fd972a4f4/bsd/net/pfkeyv2.h#L321-L343

I can fix the enum myself, of course, but I do not know whether the kernel has all required stuff.

P. S. Modern xnu has extra defines there: https://github.com/apple-oss-distributions/xnu/blob/f6217f891ac0bb64f3d375211650a4c1ff8ca1ea/bsd/net/pfkeyv2.h#L356-L386

**Comment by tobiasbrunner** [comment]
We currently don't use any of these additional macOS extensions, so if you just remove the strings after `"SADB_EXT_SASTAT"` (i.e. `"SADB_X_EXT_IPSECIF"` until `"SADB_X_EXT_MIGRATE_IPSECIF"`) to match the header, you should be fine. (I guess we could theoretically try using `SADB_EXT_MIGRATE_ADDRESS_SRC|DST` as that might be similar to `SADB_X_EXT_NEW_ADDRESS_SRC|DST` we use on FreeBSD.)

**Comment by barracuda156** [comment]
@tobiasbrunner This seems to work: https://github.com/barracuda156/strongswan/commit/034f086610d0a090f905936a37138ab1786901c9
If it looks sensible to you, it is probably committable – just a few transparent macros.

**Comment by tobiasbrunner** [comment]
According to the documentation in the header file, that macro is not intended to be used like that. `MAC_OS_X_VERSION_MIN_REQUIRED` and `MAC_OS_X_VERSION_MAX_ALLOWED` are rather constants to be defined by developers of an application to influence Apple's header files.

Why do you insist on using such an old and unmaintained version of macOS anyway? We've added the additional strings 6 years ago and it didn't cause any problems so far (of course, if your version check is to be believed, the last "new" extensions were added with 10.11, which was already EOL for 18 months at that time). So I currently don't see a reason to change anything.

**Comment by barracuda156** [comment]
> According to the documentation in the header file, that macro is not intended to be used like that.

AFAIK, it is the standard usage of it, with plenty of examples in various code bases.
https://github.com/harfbuzz/harfbuzz/blob/db63939aaaccc73f94d4535e59d90588d6419d22/src/hb-coretext-shape.cc#L219
https://github.com/FFmpeg/FFmpeg/blob/7b773aba82ea91af24e711262725a462fe71c12c/libavcodec/audiotoolboxenc.c#L73
MacPorts uses it a lot for compile-time conditions.

> Why do you insist on using such an old and unmaintained version of macOS anyway?

10.6.8 [unofficially] is the last version to run on powerpc hardware. Also MacPorts supports 10.5+, as of now, so I just match the threshold.

> of course, if your version check is to be believed

I relied on the header contents in `xnu` versions, so it is provisionally correct, but if you will accept the PR, I gonna verify it again and add links to xnu sources for the reference.

> So I currently don't see a reason to change anything.

Well, it is a one-time fix with zero maintenance cost. But up to you, of course, I can live with a local patch, if there is no interest to fix it here.

**Comment by tobiasbrunner** [comment]
> AFAIK, it is the standard usage of it, with plenty of examples in various code bases.

It doesn't seem suitable for this use case though, because it doesn't reflect the actual header contents. If not specified explicitly (or via some compiler magic, which I don't know if usually the case), `MAC_OS_X_VERSION_MIN_REQUIRED` will default to some very old versions based on the architecture. The `pfkeyv2.h` header can be a newer version depending on the actual macOS version. And since it doesn't use these or similar macros when defining the extension constants, there will still be a mismatch.

It might be safer to do something similar to the `SADB_X_EXT_IF_HW_OFFL` check on FreeBSD, where we check for one of the constants that were added as a block. That could work with the extensions on macOS too and would actually be based on the relevant header.

> 10.6.8 [unofficially] is the last version to run on powerpc hardware. Also MacPorts supports 10.5+, as of now, so I just match the threshold.

That doesn't mean there are still (new) users of strongSwan with such ancient hardware or old macOS versions. Homebrew only supports macOS versions still supported by Apple (i.e. back to 14), which sounds reasonable to me in order to reduce maintenance and testing overhead.
