### ISSUE TITLE
5.9.7 GCC build error ‘strncpy’ specified bound 16 equals destination size [-W error=stringop-truncation]

### ISSUE THREAD

**Issue by myomv100** [strongswan/strongswan#1208]
Hello everyone,

I tried to build `strongswan 5.9.7` with  `gcc (Debian 8.3.0-6) 8.3.0`

The make process fails with 
`kernel_netlink_net.c:1129:4: error: ‘strncpy’ specified bound 16 equals destination size [-W error=stringop-truncation]`
file is kernel_netlink_net.c line is 1129
https://github.com/strongswan/strongswan/blob/bcedd65a31667a25427ad6f12ccdbf88d01af3a6/src/libcharon/plugins/kernel_netlink/kernel_netlink_net.c#L1129

When I modify source code to the following the problem goes away
` strncpy(entry->ifname, name, IFNAMSIZ -1 ); `

Any idea if this is a bug or a build environment issue ?

**Comment by strongX509** [comment]
Hmm, the compilers are getting more and more paranoid ;-)

Actually we are terminating the buffer with a NUL character after the copy operation:
````
 1129: 			strncpy(entry->ifname, name, IFNAMSIZ);
 1130: 			entry->ifname[IFNAMSIZ-1] = '\0';
````
but the compiler isn't **that** intelligent. Please wait for a decision until next week when Tobias, our main developer will be back from vacation.

**Comment by myomv100** [comment]
Thanks Tobias for the detailed explaination. 
I will roll back my workarounds changes and re-compile on Debian 11 (gcc 10.2.1)
