### ISSUE TITLE
strongswan 5.9.9 doesn't compile on slackware 14.2 (64 bit)

### ISSUE THREAD

**Issue by O-ring** [strongswan/strongswan#1503]
- OS: slackware 14.2 64 bit
 - Kernel version (if applicable): 5.13.12
 - strongSwan version(s): 5.9.9

strongswan 5.9.9 doesn't compile on Slackware 14.2 64 bit (5.9.8 is fine). However strongswan 5.9.9 compiles on slackware 15.0 (64 bit)

This is the output:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../.. -I../../../../src/include -I../../../../src/libstrongswan -I../../../../src/libcharon -DROUTING_TABLE=220 -DROUTING_TABLE_PRIO=220 -rdynamic -Wno-format -Wno-format-security -Wno-implicit-fallthrough -Wno-missing-field-initializers -Wno-pointer-sign -Wno-sign-compare -Wno-type-limits -Wno-unused-parameter -g -O2 -include /tmp/STRONGSWAN/strongswan-5.9.9/config.h -MT kernel_netlink_shared.lo -MD -MP -MF .deps/kernel_netlink_shared.Tpo -c kernel_netlink_shared.c  -fPIC -DPIC -o .libs/kernel_netlink_shared.o
In file included from ../../../../src/libstrongswan/library.h:102:0,
                 from kernel_netlink_shared.h:20,
                 from kernel_netlink_shared.c:47:
kernel_netlink_shared.c: In function 'netlink_socket_create':
kernel_netlink_shared.c:665:41: error: 'SOL_NETLINK' undeclared (first use in this function)
  ignore_result(setsockopt(this->socket, SOL_NETLINK, NETLINK_CAP_ACK, &on,
                                         ^
../../../../src/libstrongswan/utils/utils.h:220:34: note: in definition of macro 'ignore_result'
 #define ignore_result(call) { if(call){}; }
                                  ^
kernel_netlink_shared.c:665:41: note: each undeclared identifier is reported only once for each function it appears in
  ignore_result(setsockopt(this->socket, SOL_NETLINK, NETLINK_CAP_ACK, &on,
                                         ^
../../../../src/libstrongswan/utils/utils.h:220:34: note: in definition of macro 'ignore_result'
 #define ignore_result(call) { if(call){}; }
                                  ^
kernel_netlink_shared.c: At top level:
cc1: warning: unrecognized command line option '-Wno-implicit-fallthrough'
Makefile:694: recipe for target 'kernel_netlink_shared.lo' failed
make[5]: *** [kernel_netlink_shared.lo] Error 1
make[5]: Leaving directory '/tmp/STRONGSWAN/strongswan-5.9.9/src/libcharon/plugins/kernel_netlink'
Makefile:2128: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/tmp/STRONGSWAN/strongswan-5.9.9/src/libcharon'
Makefile:1415: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/tmp/STRONGSWAN/strongswan-5.9.9/src/libcharon'
Makefile:540: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/STRONGSWAN/strongswan-5.9.9/src'
Makefile:605: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/STRONGSWAN/strongswan-5.9.9'
Makefile:516: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tobiasbrunner** [comment]
`SOL_NETLINK` has been defined in the kernel's `socket.h` since 2.6.14 (from 2005). I guess some C libraries don't provide it in their headers, though. In particular, glibc only added it in 2016 with 2.24. Unfortunately for you, slackware 14.2 ships glibc 2.23.

I've pushed a fix to the _1503-sol-netlink_ branch.

**Comment by O-ring** [comment]
Hello Tobias,

Thanks for the fix: I have applied the fix and now 5.9.9 compiles also on slackware 14.2

Marco
